// flow-typed signature: 2bd5f9cfdfc9345f3412846d297eed99
// flow-typed version: <<STUB>>/generact_v^0.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generact/dist/cli' {
  declare module.exports: any;
}

declare module 'generact/dist/prompts' {
  declare module.exports: any;
}

declare module 'generact/dist/types' {
  declare module.exports: any;
}

declare module 'generact/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generact/dist/cli.js' {
  declare module.exports: $Exports<'generact/dist/cli'>;
}
declare module 'generact/dist/prompts.js' {
  declare module.exports: $Exports<'generact/dist/prompts'>;
}
declare module 'generact/dist/types.js' {
  declare module.exports: $Exports<'generact/dist/types'>;
}
declare module 'generact/dist/utils.js' {
  declare module.exports: $Exports<'generact/dist/utils'>;
}
