// flow-typed signature: 8f795a467e9244f7c98424df82219969
// flow-typed version: <<STUB>>/semantic-ui-less-module-loader_v^1.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-ui-less-module-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-ui-less-module-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'semantic-ui-less-module-loader/index' {
  declare module.exports: $Exports<'semantic-ui-less-module-loader'>;
}
declare module 'semantic-ui-less-module-loader/index.js' {
  declare module.exports: $Exports<'semantic-ui-less-module-loader'>;
}
