// flow-typed signature: 97b70c86e1b381316929dea6d4075e4d
// flow-typed version: <<STUB>>/theaterjs_v^3.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'theaterjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'theaterjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'theaterjs/dist/theater' {
  declare module.exports: any;
}

declare module 'theaterjs/dist/theater.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'theaterjs/dist/theater.js' {
  declare module.exports: $Exports<'theaterjs/dist/theater'>;
}
declare module 'theaterjs/dist/theater.min.js' {
  declare module.exports: $Exports<'theaterjs/dist/theater.min'>;
}
declare module 'theaterjs/index' {
  declare module.exports: $Exports<'theaterjs'>;
}
declare module 'theaterjs/index.js' {
  declare module.exports: $Exports<'theaterjs'>;
}
