// flow-typed signature: c85773d72929abae060c002af170cccc
// flow-typed version: <<STUB>>/tsne-js_v^1.0.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tsne-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tsne-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tsne-js/build/tsne.min' {
  declare module.exports: any;
}

declare module 'tsne-js/dist/index' {
  declare module.exports: any;
}

declare module 'tsne-js/dist/joint-probabilities' {
  declare module.exports: any;
}

declare module 'tsne-js/dist/kl-divergence' {
  declare module.exports: any;
}

declare module 'tsne-js/dist/pairwise-distances' {
  declare module.exports: any;
}

declare module 'tsne-js/dist/randn' {
  declare module.exports: any;
}

declare module 'tsne-js/example/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tsne-js/build/tsne.min.js' {
  declare module.exports: $Exports<'tsne-js/build/tsne.min'>;
}
declare module 'tsne-js/dist/index.js' {
  declare module.exports: $Exports<'tsne-js/dist/index'>;
}
declare module 'tsne-js/dist/joint-probabilities.js' {
  declare module.exports: $Exports<'tsne-js/dist/joint-probabilities'>;
}
declare module 'tsne-js/dist/kl-divergence.js' {
  declare module.exports: $Exports<'tsne-js/dist/kl-divergence'>;
}
declare module 'tsne-js/dist/pairwise-distances.js' {
  declare module.exports: $Exports<'tsne-js/dist/pairwise-distances'>;
}
declare module 'tsne-js/dist/randn.js' {
  declare module.exports: $Exports<'tsne-js/dist/randn'>;
}
declare module 'tsne-js/example/worker.js' {
  declare module.exports: $Exports<'tsne-js/example/worker'>;
}
