// flow-typed signature: d9fe475aa7f028b2858839e61d030b02
// flow-typed version: <<STUB>>/@trainline/react-skeletor_v^0.1.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@trainline/react-skeletor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@trainline/react-skeletor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@trainline/react-skeletor/lib/createSkeletonElement' {
  declare module.exports: any;
}

declare module '@trainline/react-skeletor/lib/createSkeletonProvider' {
  declare module.exports: any;
}

declare module '@trainline/react-skeletor/lib/index' {
  declare module.exports: any;
}

declare module '@trainline/react-skeletor/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@trainline/react-skeletor/lib/createSkeletonElement.js' {
  declare module.exports: $Exports<'@trainline/react-skeletor/lib/createSkeletonElement'>;
}
declare module '@trainline/react-skeletor/lib/createSkeletonProvider.js' {
  declare module.exports: $Exports<'@trainline/react-skeletor/lib/createSkeletonProvider'>;
}
declare module '@trainline/react-skeletor/lib/index.js' {
  declare module.exports: $Exports<'@trainline/react-skeletor/lib/index'>;
}
declare module '@trainline/react-skeletor/lib/utils.js' {
  declare module.exports: $Exports<'@trainline/react-skeletor/lib/utils'>;
}
