// flow-typed signature: ec25cbb024aae0f1ef034f1363859a33
// flow-typed version: <<STUB>>/@cerebral/firebase_v^0.0.0-beta.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cerebral/firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cerebral/firebase/lib/createOnChildAdded' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/createOnChildChanged' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/createOnChildRemoved' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/createOnValue' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/createTask' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/createUserWithEmailAndPassword' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/delete' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/deleteUser' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/errors' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/getUser' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/helpers' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/index' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/linkWithFacebook' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/linkWithGithub' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/linkWithGoogle' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/onDisconnect' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/cancelOnDisconnect' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/createUserWithEmailAndPassword' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/delete' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/deleteUser' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/getUser' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/index' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/linkWithFacebook' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/linkWithGithub' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/linkWithGoogle' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/off' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/onChildAdded' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/onChildChanged' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/onChildRemoved' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/onValue' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/push' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/put' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/remove' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/sendPasswordResetEmail' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/set' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/setOnDisconnect' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/signInAnonymously' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/signInWithEmailAndPassword' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/signInWithFacebook' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/signInWithGithub' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/signInWithGoogle' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/signOut' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/task' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/transaction' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/update' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/operators/value' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/push' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/put' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/remove' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/sendPasswordResetEmail' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/set' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/signInAnonymously' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/signInWithEmailAndPassword' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/signInWithFacebook' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/signInWithGithub' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/signInWithGoogle' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/signOut' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/transaction' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/update' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/lib/value' {
  declare module.exports: any;
}

declare module '@cerebral/firebase/operators' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cerebral/firebase/lib/createOnChildAdded.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/createOnChildAdded'>;
}
declare module '@cerebral/firebase/lib/createOnChildChanged.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/createOnChildChanged'>;
}
declare module '@cerebral/firebase/lib/createOnChildRemoved.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/createOnChildRemoved'>;
}
declare module '@cerebral/firebase/lib/createOnValue.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/createOnValue'>;
}
declare module '@cerebral/firebase/lib/createTask.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/createTask'>;
}
declare module '@cerebral/firebase/lib/createUserWithEmailAndPassword.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/createUserWithEmailAndPassword'>;
}
declare module '@cerebral/firebase/lib/delete.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/delete'>;
}
declare module '@cerebral/firebase/lib/deleteUser.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/deleteUser'>;
}
declare module '@cerebral/firebase/lib/errors.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/errors'>;
}
declare module '@cerebral/firebase/lib/getUser.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/getUser'>;
}
declare module '@cerebral/firebase/lib/helpers.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/helpers'>;
}
declare module '@cerebral/firebase/lib/index.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/index'>;
}
declare module '@cerebral/firebase/lib/linkWithFacebook.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/linkWithFacebook'>;
}
declare module '@cerebral/firebase/lib/linkWithGithub.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/linkWithGithub'>;
}
declare module '@cerebral/firebase/lib/linkWithGoogle.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/linkWithGoogle'>;
}
declare module '@cerebral/firebase/lib/onDisconnect.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/onDisconnect'>;
}
declare module '@cerebral/firebase/lib/operators/cancelOnDisconnect.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/cancelOnDisconnect'>;
}
declare module '@cerebral/firebase/lib/operators/createUserWithEmailAndPassword.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/createUserWithEmailAndPassword'>;
}
declare module '@cerebral/firebase/lib/operators/delete.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/delete'>;
}
declare module '@cerebral/firebase/lib/operators/deleteUser.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/deleteUser'>;
}
declare module '@cerebral/firebase/lib/operators/getUser.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/getUser'>;
}
declare module '@cerebral/firebase/lib/operators/index.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/index'>;
}
declare module '@cerebral/firebase/lib/operators/linkWithFacebook.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/linkWithFacebook'>;
}
declare module '@cerebral/firebase/lib/operators/linkWithGithub.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/linkWithGithub'>;
}
declare module '@cerebral/firebase/lib/operators/linkWithGoogle.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/linkWithGoogle'>;
}
declare module '@cerebral/firebase/lib/operators/off.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/off'>;
}
declare module '@cerebral/firebase/lib/operators/onChildAdded.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/onChildAdded'>;
}
declare module '@cerebral/firebase/lib/operators/onChildChanged.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/onChildChanged'>;
}
declare module '@cerebral/firebase/lib/operators/onChildRemoved.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/onChildRemoved'>;
}
declare module '@cerebral/firebase/lib/operators/onValue.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/onValue'>;
}
declare module '@cerebral/firebase/lib/operators/push.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/push'>;
}
declare module '@cerebral/firebase/lib/operators/put.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/put'>;
}
declare module '@cerebral/firebase/lib/operators/remove.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/remove'>;
}
declare module '@cerebral/firebase/lib/operators/sendPasswordResetEmail.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/sendPasswordResetEmail'>;
}
declare module '@cerebral/firebase/lib/operators/set.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/set'>;
}
declare module '@cerebral/firebase/lib/operators/setOnDisconnect.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/setOnDisconnect'>;
}
declare module '@cerebral/firebase/lib/operators/signInAnonymously.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/signInAnonymously'>;
}
declare module '@cerebral/firebase/lib/operators/signInWithEmailAndPassword.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/signInWithEmailAndPassword'>;
}
declare module '@cerebral/firebase/lib/operators/signInWithFacebook.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/signInWithFacebook'>;
}
declare module '@cerebral/firebase/lib/operators/signInWithGithub.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/signInWithGithub'>;
}
declare module '@cerebral/firebase/lib/operators/signInWithGoogle.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/signInWithGoogle'>;
}
declare module '@cerebral/firebase/lib/operators/signOut.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/signOut'>;
}
declare module '@cerebral/firebase/lib/operators/task.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/task'>;
}
declare module '@cerebral/firebase/lib/operators/transaction.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/transaction'>;
}
declare module '@cerebral/firebase/lib/operators/update.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/update'>;
}
declare module '@cerebral/firebase/lib/operators/value.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/operators/value'>;
}
declare module '@cerebral/firebase/lib/push.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/push'>;
}
declare module '@cerebral/firebase/lib/put.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/put'>;
}
declare module '@cerebral/firebase/lib/remove.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/remove'>;
}
declare module '@cerebral/firebase/lib/sendPasswordResetEmail.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/sendPasswordResetEmail'>;
}
declare module '@cerebral/firebase/lib/set.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/set'>;
}
declare module '@cerebral/firebase/lib/signInAnonymously.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/signInAnonymously'>;
}
declare module '@cerebral/firebase/lib/signInWithEmailAndPassword.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/signInWithEmailAndPassword'>;
}
declare module '@cerebral/firebase/lib/signInWithFacebook.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/signInWithFacebook'>;
}
declare module '@cerebral/firebase/lib/signInWithGithub.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/signInWithGithub'>;
}
declare module '@cerebral/firebase/lib/signInWithGoogle.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/signInWithGoogle'>;
}
declare module '@cerebral/firebase/lib/signOut.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/signOut'>;
}
declare module '@cerebral/firebase/lib/transaction.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/transaction'>;
}
declare module '@cerebral/firebase/lib/update.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/update'>;
}
declare module '@cerebral/firebase/lib/value.js' {
  declare module.exports: $Exports<'@cerebral/firebase/lib/value'>;
}
declare module '@cerebral/firebase/operators.js' {
  declare module.exports: $Exports<'@cerebral/firebase/operators'>;
}
