// flow-typed signature: 2e5f8c3356b1e2125a0d5e4814ed1119
// flow-typed version: <<STUB>>/@cerebral/forms_v^0.0.0-beta.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/forms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cerebral/forms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cerebral/forms/lib/form' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/helpers/formToJSON' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/helpers/getFormFields' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/helpers/getInvalidFormFields' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/helpers/resetForm' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/index' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/operators/index' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/operators/isValidForm' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/operators/resetForm' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/operators/setField' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/rules' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/utils/checkHasValue' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/utils/runValidation' {
  declare module.exports: any;
}

declare module '@cerebral/forms/lib/utils/validate' {
  declare module.exports: any;
}

declare module '@cerebral/forms/operators' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/field.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/form' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/form.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/formToJSON' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/formToJSON.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/getFormFields' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/getFormFields.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/getInvalidFormFields' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/getInvalidFormFields.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/resetForm' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/helpers/resetForm.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/index' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/index.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/operators/index' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/operators/isValidForm' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/operators/isValidForm.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/operators/resetForm' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/operators/resetForm.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/operators/setField' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/operators/setField.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/rules' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/rules.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/util.test' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/utils/checkHasValue' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/utils/runValidation' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/utils/validate' {
  declare module.exports: any;
}

declare module '@cerebral/forms/src/utils/validate.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cerebral/forms/lib/form.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/form'>;
}
declare module '@cerebral/forms/lib/helpers/formToJSON.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/helpers/formToJSON'>;
}
declare module '@cerebral/forms/lib/helpers/getFormFields.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/helpers/getFormFields'>;
}
declare module '@cerebral/forms/lib/helpers/getInvalidFormFields.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/helpers/getInvalidFormFields'>;
}
declare module '@cerebral/forms/lib/helpers/resetForm.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/helpers/resetForm'>;
}
declare module '@cerebral/forms/lib/index.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/index'>;
}
declare module '@cerebral/forms/lib/operators/index.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/operators/index'>;
}
declare module '@cerebral/forms/lib/operators/isValidForm.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/operators/isValidForm'>;
}
declare module '@cerebral/forms/lib/operators/resetForm.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/operators/resetForm'>;
}
declare module '@cerebral/forms/lib/operators/setField.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/operators/setField'>;
}
declare module '@cerebral/forms/lib/rules.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/rules'>;
}
declare module '@cerebral/forms/lib/utils/checkHasValue.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/utils/checkHasValue'>;
}
declare module '@cerebral/forms/lib/utils/runValidation.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/utils/runValidation'>;
}
declare module '@cerebral/forms/lib/utils/validate.js' {
  declare module.exports: $Exports<'@cerebral/forms/lib/utils/validate'>;
}
declare module '@cerebral/forms/operators.js' {
  declare module.exports: $Exports<'@cerebral/forms/operators'>;
}
declare module '@cerebral/forms/src/field.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/field.test'>;
}
declare module '@cerebral/forms/src/form.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/form'>;
}
declare module '@cerebral/forms/src/form.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/form.test'>;
}
declare module '@cerebral/forms/src/helpers/formToJSON.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/formToJSON'>;
}
declare module '@cerebral/forms/src/helpers/formToJSON.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/formToJSON.test'>;
}
declare module '@cerebral/forms/src/helpers/getFormFields.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/getFormFields'>;
}
declare module '@cerebral/forms/src/helpers/getFormFields.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/getFormFields.test'>;
}
declare module '@cerebral/forms/src/helpers/getInvalidFormFields.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/getInvalidFormFields'>;
}
declare module '@cerebral/forms/src/helpers/getInvalidFormFields.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/getInvalidFormFields.test'>;
}
declare module '@cerebral/forms/src/helpers/resetForm.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/resetForm'>;
}
declare module '@cerebral/forms/src/helpers/resetForm.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/helpers/resetForm.test'>;
}
declare module '@cerebral/forms/src/index.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/index'>;
}
declare module '@cerebral/forms/src/index.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/index.test'>;
}
declare module '@cerebral/forms/src/operators/index.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/operators/index'>;
}
declare module '@cerebral/forms/src/operators/isValidForm.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/operators/isValidForm'>;
}
declare module '@cerebral/forms/src/operators/isValidForm.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/operators/isValidForm.test'>;
}
declare module '@cerebral/forms/src/operators/resetForm.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/operators/resetForm'>;
}
declare module '@cerebral/forms/src/operators/resetForm.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/operators/resetForm.test'>;
}
declare module '@cerebral/forms/src/operators/setField.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/operators/setField'>;
}
declare module '@cerebral/forms/src/operators/setField.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/operators/setField.test'>;
}
declare module '@cerebral/forms/src/rules.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/rules'>;
}
declare module '@cerebral/forms/src/rules.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/rules.test'>;
}
declare module '@cerebral/forms/src/util.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/util.test'>;
}
declare module '@cerebral/forms/src/utils/checkHasValue.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/utils/checkHasValue'>;
}
declare module '@cerebral/forms/src/utils/runValidation.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/utils/runValidation'>;
}
declare module '@cerebral/forms/src/utils/validate.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/utils/validate'>;
}
declare module '@cerebral/forms/src/utils/validate.test.js' {
  declare module.exports: $Exports<'@cerebral/forms/src/utils/validate.test'>;
}
