// flow-typed signature: 99f24ff425b245a382936c9a5d1e52e9
// flow-typed version: <<STUB>>/@react-pdf/core_v^0.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-pdf/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-pdf/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-pdf/core/lib/elements/Base' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Catalog' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Document' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Font' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/GraphicState' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Image' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/index' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Info' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Page' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Pages' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/PDFEntry' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Rectangle' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Resources' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Root' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/Text' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/elements/View' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/index' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/pdf/convert' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/pdf/index' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/renderer' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/Stylesheet/index' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/colors' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/image' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/jpeg' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/jpg' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/math' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/pageSizes' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/pdf' {
  declare module.exports: any;
}

declare module '@react-pdf/core/lib/utils/yogaValue' {
  declare module.exports: any;
}

declare module '@react-pdf/core/specs/imageSpec' {
  declare module.exports: any;
}

declare module '@react-pdf/core/specs/pageSpec' {
  declare module.exports: any;
}

declare module '@react-pdf/core/specs/testRenderer' {
  declare module.exports: any;
}

declare module '@react-pdf/core/specs/textSpec' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/elements/Base' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/elements/Document' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/elements/Image' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/elements/index' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/elements/Page' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/elements/Text' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/elements/View' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/index' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/renderer' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/stylesheet/index' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/utils/image' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/utils/jpeg' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/utils/pageSizes' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/utils/pdf' {
  declare module.exports: any;
}

declare module '@react-pdf/core/src/utils/yogaValue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-pdf/core/lib/elements/Base.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Base'>;
}
declare module '@react-pdf/core/lib/elements/Catalog.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Catalog'>;
}
declare module '@react-pdf/core/lib/elements/Document.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Document'>;
}
declare module '@react-pdf/core/lib/elements/Font.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Font'>;
}
declare module '@react-pdf/core/lib/elements/GraphicState.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/GraphicState'>;
}
declare module '@react-pdf/core/lib/elements/Image.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Image'>;
}
declare module '@react-pdf/core/lib/elements/index.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/index'>;
}
declare module '@react-pdf/core/lib/elements/Info.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Info'>;
}
declare module '@react-pdf/core/lib/elements/Page.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Page'>;
}
declare module '@react-pdf/core/lib/elements/Pages.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Pages'>;
}
declare module '@react-pdf/core/lib/elements/PDFEntry.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/PDFEntry'>;
}
declare module '@react-pdf/core/lib/elements/Rectangle.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Rectangle'>;
}
declare module '@react-pdf/core/lib/elements/Resources.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Resources'>;
}
declare module '@react-pdf/core/lib/elements/Root.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Root'>;
}
declare module '@react-pdf/core/lib/elements/Text.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/Text'>;
}
declare module '@react-pdf/core/lib/elements/View.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/elements/View'>;
}
declare module '@react-pdf/core/lib/index.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/index'>;
}
declare module '@react-pdf/core/lib/pdf/convert.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/pdf/convert'>;
}
declare module '@react-pdf/core/lib/pdf/index.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/pdf/index'>;
}
declare module '@react-pdf/core/lib/renderer.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/renderer'>;
}
declare module '@react-pdf/core/lib/Stylesheet/index.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/Stylesheet/index'>;
}
declare module '@react-pdf/core/lib/utils/colors.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/colors'>;
}
declare module '@react-pdf/core/lib/utils/image.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/image'>;
}
declare module '@react-pdf/core/lib/utils/jpeg.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/jpeg'>;
}
declare module '@react-pdf/core/lib/utils/jpg.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/jpg'>;
}
declare module '@react-pdf/core/lib/utils/math.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/math'>;
}
declare module '@react-pdf/core/lib/utils/pageSizes.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/pageSizes'>;
}
declare module '@react-pdf/core/lib/utils/pdf.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/pdf'>;
}
declare module '@react-pdf/core/lib/utils/yogaValue.js' {
  declare module.exports: $Exports<'@react-pdf/core/lib/utils/yogaValue'>;
}
declare module '@react-pdf/core/specs/imageSpec.js' {
  declare module.exports: $Exports<'@react-pdf/core/specs/imageSpec'>;
}
declare module '@react-pdf/core/specs/pageSpec.js' {
  declare module.exports: $Exports<'@react-pdf/core/specs/pageSpec'>;
}
declare module '@react-pdf/core/specs/testRenderer.js' {
  declare module.exports: $Exports<'@react-pdf/core/specs/testRenderer'>;
}
declare module '@react-pdf/core/specs/textSpec.js' {
  declare module.exports: $Exports<'@react-pdf/core/specs/textSpec'>;
}
declare module '@react-pdf/core/src/elements/Base.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/elements/Base'>;
}
declare module '@react-pdf/core/src/elements/Document.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/elements/Document'>;
}
declare module '@react-pdf/core/src/elements/Image.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/elements/Image'>;
}
declare module '@react-pdf/core/src/elements/index.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/elements/index'>;
}
declare module '@react-pdf/core/src/elements/Page.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/elements/Page'>;
}
declare module '@react-pdf/core/src/elements/Text.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/elements/Text'>;
}
declare module '@react-pdf/core/src/elements/View.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/elements/View'>;
}
declare module '@react-pdf/core/src/index.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/index'>;
}
declare module '@react-pdf/core/src/renderer.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/renderer'>;
}
declare module '@react-pdf/core/src/stylesheet/index.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/stylesheet/index'>;
}
declare module '@react-pdf/core/src/utils/image.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/utils/image'>;
}
declare module '@react-pdf/core/src/utils/jpeg.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/utils/jpeg'>;
}
declare module '@react-pdf/core/src/utils/pageSizes.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/utils/pageSizes'>;
}
declare module '@react-pdf/core/src/utils/pdf.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/utils/pdf'>;
}
declare module '@react-pdf/core/src/utils/yogaValue.js' {
  declare module.exports: $Exports<'@react-pdf/core/src/utils/yogaValue'>;
}
